# 1. Write a Python Program to Add Two Matrices?

In [27]:
import numpy as np

# The first matrix will be
P = np.array([[8,9,3],
              [3 ,5, 6],
              [4 ,6, 3]])

#The second matrix will be

Q = np.array([[2,8,2],
              [6,8,3],
              [3,4,2]])
np.add(P,Q)

array([[10, 17,  5],
       [ 9, 13,  9],
       [ 7, 10,  5]])

# 2. Write a Python Program to Multiply Two Matrices?

In [28]:
# multiplication of two matrix using @ operator

import numpy as np

# The first matrix will be
P = np.array([[8,9,3],
              [3 ,5, 6],
              [4 ,6, 3]])

#The second matrix will be

Q = np.array([[2,8,2],
              [6,8,3],
              [3,4,2]])
print(P@Q)

[[ 79 148  49]
 [ 54  88  33]
 [ 53  92  32]]


In [29]:
# multiplication of two matrix using matmul function 
import numpy as np

P = np.array([[8,9,3],
              [3 ,5, 6],
              [4 ,6, 3]])


#The second matrix will be

Q = np.array([[2,8,2],
              [6,8,3],
              [3,4,2]])
np.matmul(P,Q)    

array([[ 79, 148,  49],
       [ 54,  88,  33],
       [ 53,  92,  32]])

# 3. Write a Python Program to Transpose a Matrix?

In [30]:
P = np.array([[8,9,3],
              [3 ,5, 6],
              [4 ,6, 3]])

P.transpose()

array([[8, 3, 4],
       [9, 5, 6],
       [3, 6, 3]])

# 4. Write a Python Program to sort Words in an Alphabatical Order ?

In [31]:
def sort_string():
    words_= input("Enter a String: ").title()
    sorted_words = sorted(words_.split(' '))
    print(sorted_words)

sortString()

Enter a String: ved is Sukhoi pilot 
 Is Pilot Sukhoi Ved


# 5. Write a Python Program to Remove Punctuation From a String?

In [1]:
# panchuation- the marks, such as full stop, comma, and brackets, used in writing to separate sentences and their elements and to clarify meaning.
def remove_panchuation():
    punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''
    string_with_panchuation  = input('Enter a String with panchuation : ').title()
    string_without_panchuation = ''
    for i in string_with_panchuation :
        if i not in punctuations:
            string_without_panchuation = string_without_panchuation+i
    print(string_without_panchuation)
    
remove_panchuation()

Enter a String with panchuation : sanna @ is # strong ^ (%) girl
Sanna  Is  Strong   Girl
